# Generated by Django 5.0.6 on 2026-04-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(check=models.Q(('order_id__gt', 0)), name='shipping_order_id_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(check=models.Q(('payment_id__gt', 0)), name='shipping_payment_id_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(check=models.Q(('user_id__gt', 0)), name='shipping_user_id_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('order_id',), name='unique_shipment_per_order'),
        ),
    ]
